### ISSUE TITLE
Dist::Zilla::Plugin::Test::Compile has fixed a problem, please make new release

### ISSUE THREAD

**Issue by mohawk2** [rwstauner/Config-MVP-Slicer#2]
`Dist::Zilla::Plugin::Test::Compile` supplies `00-compile.t` in your distro, which fails on "perl in space". This problem has long been fixed. Please could you make a new release which will include the fixed code?

**Comment by rwstauner** [comment]
new release coming up.  what is "perl in space"?

**Comment by mohawk2** [comment]
Thanks! It's Perl installed in a directory with a space in its name.

**Comment by karenetheridge** [comment]
perl! in! spaaaaaace!

**Comment by rwstauner** [comment]
0.303 is up.
